### Análisis preliminar de los datos

In [2]:
# Importaciones
import pandas as pd

pd.set_option('display.max_columns', None)

In [10]:
# Leer el archivo, elimino la columna “Unnamed: 0” generada automáticamente por pandas con index_col
df_raw = pd.read_csv("../data_raw/bank-additional.csv", index_col=0)
df_raw.head()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

In [11]:
df_raw.shape

(43000, 23)

In [12]:
print (f'El número de filas del conjunto de datos es : {df_raw.shape[0]}')
print (f'El número de columnas del conjunto de datos es : {df_raw.shape[1]}')

El número de filas del conjunto de datos es : 43000
El número de columnas del conjunto de datos es : 23

In [13]:
df_raw.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome',
       'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m',
       'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_'],
      dtype='object')

In [14]:
df_raw.sample()

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
15067,27.0,blue-collar,SINGLE,basic.9y,0.0,1.0,0.0,cellular,818,1,999,0,NONEXISTENT,1.4,"93,918","-42,7","4,958","5228,1",no,2-febrero-2018,45.259,-81.721,ba495ec7-be2b-4cc4-8425-4627174d3e9d

In [15]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43000 entries, 0 to 27570
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             37880 non-null  float64
 1   job             42655 non-null  object
 2   marital         42915 non-null  object
 3   education       41193 non-null  object
 4   default         34019 non-null  float64
 5   housing         41974 non-null  float64
 6   loan            41974 non-null  float64
 7   contact         43000 non-null  object
 8   duration        43000 non-null  int64
 9   campaign        43000 non-null  int64
 10  pdays           43000 non-null  int64
 11  previous        43000 non-null  int64
 12  poutcome        43000 non-null  object
 13  emp.var.rate    43000 non-null  float64
 14  cons.price.idx  42529 non-null  object
 15  cons.conf.idx   43000 non-null  object
 16  euribor3m       33744 non-null  object
 17  nr.employed     43000 non-null  object
 18  y               43000 non-null  object
 19  date            42752 non-null  object
 20  latitude        43000 non-null  float64
 21  longitude       43000 non-null  float64
 22  id_             43000 non-null  object
dtypes: float64(7), int64(4), object(12)
memory usage: 7.9+ MB

In [16]:
# Crear un dataframe alternativo para trabajar
df = df_raw.copy()

In [17]:
df.sample(3)

,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
14177,30.0,blue-collar,MARRIED,high.school,NaN,1.0,0.0,cellular,1153,3,999,0,NONEXISTENT,1.4,"93,918","-42,7",NaN,"5228,1",yes,4-octubre-2017,32.847,-124.262,2cbd7812-e437-403a-a298-ed7155636cb5
32474,34.0,admin.,MARRIED,high.school,NaN,0.0,0.0,cellular,267,2,999,0,NONEXISTENT,-1.8,"92,893","-46,2","1,313","5099,1",no,30-marzo-2015,27.381,-91.076,6faf2a0d-a463-40ce-a987-c0826ed1c550
29658,47.0,self-employed,MARRIED,university.degree,0.0,0.0,0.0,cellular,145,1,999,0,NONEXISTENT,-1.8,"93,075","-47,1","1,405","5099,1",no,15-julio-2019,43.074,-104.255,b64c95b3-d2e8-434b-a3c8-3dec1a7e13f3

In [18]:
# Guardo archivo
df.to_csv("../data_processed/ba_transformacion.csv", index=False)